# Generated by Django 5.2.3 on 2025-06-26 07:58

import diary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(default=diary.models.random_color, max_length=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(default=diary.models.random_color, max_length=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "subregion",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "manager",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                ("ta_date", models.DateField(blank=True, null=True)),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("fu_date", models.DateField(blank=True, null=True)),
                (
                    "possibility",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "amount",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("memo", models.TextField(blank=True, default="", null=True)),
                ("order", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="diary.category",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="diary.region",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="diary.salesstatus",
                    ),
                ),
            ],
        ),
    ]
