# Generated by Django 5.2.3 on 2025-06-27 00:59

from django.db import migrations


def create_attribute_types(apps, schema_editor):
    AttributeType = apps.get_model('diary', 'AttributeType')
    
    attribute_types = [
        'text',
        'datetime', 
        'dropdown',
        'region',
        'region_detail'
    ]
    
    for attr_type in attribute_types:
        AttributeType.objects.get_or_create(name=attr_type)


def reverse_create_attribute_types(apps, schema_editor):
    AttributeType = apps.get_model('diary', 'AttributeType')
    
    attribute_types = [
        'text',
        'datetime', 
        'dropdown',
        'region',
        'region_detail'
    ]
    
    for attr_type in attribute_types:
        AttributeType.objects.filter(name=attr_type).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_attributetype_user_attribute_attributevalue_and_more"),
    ]

    operations = [
        migrations.RunPython(create_attribute_types, reverse_create_attribute_types),
    ]
