# Generated by Django 5.2.3 on 2025-06-25 09:17

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesstatus",
            name="color",
            field=models.CharField(default=diary.models.random_color, max_length=7),
        ),
    ]
