# Generated by Django 5.2.3 on 2025-06-27 01:05

from django.db import migrations


def create_base_attributes(apps, schema_editor):
    BaseAttribute = apps.get_model('diary', 'BaseAttribute')
    AttributeType = apps.get_model('diary', 'AttributeType')
    
    # Get attribute types
    text_type = AttributeType.objects.get(name='text')
    dropdown_type = AttributeType.objects.get(name='dropdown')
    datetime_type = AttributeType.objects.get(name='datetime')
    region_type = AttributeType.objects.get(name='region')
    region_detail_type = AttributeType.objects.get(name='region_detail')
    
    # Define base attributes with their types
    base_attributes = [
        ('이름', text_type),
        ('구분', dropdown_type),
        ('지역', region_type),
        ('상세지역', region_detail_type),
        ('주소', text_type),
        ('담당자', text_type),
        ('연락처', text_type),
        ('이메일', text_type),
        ('TA', datetime_type),
        ('미팅', datetime_type),
        ('F/U 일정', datetime_type),
        ('영업진행', dropdown_type),
        ('가능성', text_type),
        ('매출', text_type),
    ]
    
    for name, attr_type in base_attributes:
        BaseAttribute.objects.get_or_create(
            name=name,
            defaults={'attributeType': attr_type}
        )


def reverse_create_base_attributes(apps, schema_editor):
    BaseAttribute = apps.get_model('diary', 'BaseAttribute')
    
    base_attribute_names = [
        '이름', '구분', '지역', '상세지역', '주소', '담당자', 
        '연락처', '이메일', 'TA', '미팅', 'F/U 일정', 
        '영업진행', '가능성', '매출'
    ]
    
    for name in base_attribute_names:
        BaseAttribute.objects.filter(name=name).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_add_attribute_types"),
    ]

    operations = [
        migrations.RunPython(create_base_attributes, reverse_create_base_attributes),
    ]
