# Generated by Django 5.2.3 on 2025-06-27 01:14

from django.db import migrations

def create_default_user(apps, schema_editor):
    User = apps.get_model('diary', 'User')
    User.objects.get_or_create(
        name='default',
        defaults={
            'email': 'default@example.com',
            'password': 'defaultpassword',
        }
    )

def reverse_create_default_user(apps, schema_editor):
    User = apps.get_model('diary', 'User')
    User.objects.filter(name='default', email='default@example.com').delete()

class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_add_base_attributes"),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_create_default_user),
    ]
